ELEARN/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("school.urls")),
    path('teacher/', include("teacher.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path
from .import views 

app_name = "teacher"
urlpatterns=[
    path('register',views.RegisterTeacherView.as_view(),name='register'),
    path('login',views.LoginView.as_view(),name='login'),
    path('teachers',views.TeachersView.as_view(),name='teachersview'),
    path('createcourse',views.CreateCourseView.as_view(),name='createcourse'),
    path('profile/<str:pk>',views.TeachersDetailsView.as_view(),name="profile"),
    path('createlesson',views.CreateLessonView.as_view(),name="createlesson"),
    path('lessons/<str:pk>',views.LessonView.as_view(),name="lessons"),
    path('lessondetails/<str:pk>',views.LessonDetailView.as_view(),name="lessondetails"),
    path('courses',views.CourseView.as_view(),name="courses"),
    path('update/<str:pk>',views.UpdateCourseView.as_view(),name="update"),
    path('deletecourse/<str:pk>',views.DeleteCourseView.as_view(),name="deletecourse"),
    path('updatelesson/<str:pk>',views.UpdateLessonView.as_view(),name="updatelesson"),
    path('deletelesson/<str:pk>',views.DeleteLessonView.as_view(),name="deletelesson"),
    # path('logout',views.LogoutView.as_view(),name='logout'),
] 

teacher/models.py
from django.db import models
from school.models import MyUser
from django.urls import reverse

# Create your models here.
class Course(models.Model):
    course_name=models.CharField(max_length=100)
    course_code=models.IntegerField(unique=True)
    lecturer=models.OneToOneField(MyUser,on_delete=models.CASCADE)
    course_description=models.CharField(max_length=100)
    duration=models.FloatField(null=True)
    capacity=models.IntegerField(null=True)
    photo=models.ImageField(upload_to="teacher",blank=True)

    def get_lessons(self):
        return self.lesson_set.all()

    def get_absolute_url(self):
        return reverse('teacher:courses')

    
    def __str__(self):
        return self.course_name

class Lesson(models.Model):
    lesson_code=models.CharField(max_length=100,unique=True)
    lesson_number=models.CharField(max_length=50,null=True,unique=True)
    lesson_title=models.CharField(max_length=50,null=True)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    lesson_description=models.CharField(max_length=100)
    video=models.FileField(upload_to="teacher",blank=True)

    def __str__(self):
        return self.lesson_title

teacher/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput

from teacher.models import Course

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        widgets = {
            'course_name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Name'
                }),
            'course_code': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                }),
            'course_description': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                }),
            'capacity': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                }),
            'duration': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                })
        }

class UPDATE_LESSON(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        widgets = {
            'course_name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Name'
                }),
            'course_code': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                }),
            'course_description': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                }),
            'capacity': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                }),
            'duration': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Code'
                })
        }

teacher/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from teacher.forms import CourseForm

from django.urls import reverse_lazy
from django.urls import reverse
# Create your views here.
from re import template
from django.shortcuts import render,redirect,get_object_or_404,HttpResponseRedirect
from django.views.generic import View
from school.models   import MyUser
from teacher.models import Course,Lesson
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from teacher.dec import staff_only
from django.utils.decorators import method_decorator

# Create your views here.



class RegisterTeacherView(View):
    template_name="teacher/create_teacher.html"
    def get(self,request):
        return render(request,self.template_name)

    def post(self, request, *args, **kwargs):
        # photo = request.FILES.get("photo")
        email= request.POST.get("email_address")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        phone=request.POST.get("phone")
        photo = request.POST.get("photo")
        address = request.POST.get("address")
        password = request.POST.get("password")
        repeat_password = request.POST.get("repeat_password")
        index = request.POST.get("index")


        if password != repeat_password:
            messages.add_message(request, messages.ERROR,
                                 "Passwords do not match.")
            return redirect("teacher:register")

        elif MyUser.objects.filter(phone=phone).exists():
            messages.error(request, 'Phone number already exists.')
            return redirect(request.META.get("HTTP_REFERER"))
            
           
               
               
        else:
            teacher = MyUser.objects.create(
               first_name=first_name,last_name=last_name,
               phone=phone,photo=photo,address=address, 
               email=email,index_number=index
            )
            teacher.photo = request.FILES.get('photo')
            teacher.is_staff=True
            teacher.is_superuser=True
            teacher.set_password(password)
           
            teacher.save()
            return redirect("school:index")

       
class LoginView(View):
    template_name = "teacher/login.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email_address")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)

        if user is not None and user.is_staff:
            login(request, user)
            redirect_url = "school:index"
            return redirect(redirect_url)
        else:
            messages.add_message(request, messages.ERROR,
                                 "Invalid credentials")
            return render(request, self.template_name)


class TeachersView(View):
    template_name="teacher/teachersview.html"

    @method_decorator(staff_only())
    def get(self, request, *args, **kwargs):
        context={"teachers":MyUser.objects.all()}
        return render(request,self.template_name,context)


class TeachersDetailsView(View):
    template_name="teacher/profile.html"

    @method_decorator(staff_only())
    def get(self, request,pk,*args, **kwargs):
        teachers=get_object_or_404(MyUser,index_number=pk)
        context={"profile":teachers}
        return render(request,self.template_name,context)


class CourseView(View):
    template_name="teacher/courselist.html"

    @method_decorator(staff_only())
    def get(self, request,*args, **kwargs):
        context={'course':Course.objects.all()}
        return render(request,self.template_name,context)


class UpdateCourseView(UpdateView):
    model = Course
    # fields = ['course_name','course_code','course_name','lecturer','course_description','duration','capacity','photo']
    template_name = 'teacher/update.html'
    form_class=CourseForm

    @method_decorator(staff_only())
    def get_absolute_url(self):
        return reverse('courses')
     

#    , args=[str(self.id)]



    
    

       
        
        
        

        


class CreateCourseView(View):
    template_name="teacher/create_course.html"

    @method_decorator(staff_only())
    def get(self,request):
        context={"myuser":MyUser.objects.all()}
        return render(request,self.template_name,context)

    @method_decorator(staff_only())
    def post(self, request, *args, **kwargs):
        # photo = request.FILES.get("photo")
        lecturer= request.POST.get("lecturer")
        course_name = request.POST.get("name")
        course_code = request.POST.get("code")
        capacity=request.POST.get("capacity")
        duration=request.POST.get("duration")
        description=request.POST.get("duration")
        myuser_object=MyUser.objects.get(first_name=lecturer)

        if Course.objects.filter(course_code=course_code).exists():
            messages.error(request, 'course_code already exists.')
            return redirect(request.META.get("HTTP_REFERER"))
        

        else:
            teacher = Course.objects.create(
            course_name=course_name,course_code=course_code,
            lecturer=myuser_object,
            course_description=description,duration=duration,
            capacity=capacity
            )
        teacher.photo=request.FILES.get('photo')
        teacher.save()
        return redirect("school:course")


class CreateLessonView(View):
    template_name="teacher/createlesson.html"
    @method_decorator(staff_only())
    def get(self,request,*args, **kwargs):
        context={"course":Course.objects.all()}
        return render(request,self.template_name,context)

    @method_decorator(staff_only())
    def post(self, request, *args, **kwargs):
        courselesson=request.POST.get("course")
        lesson_code= request.POST.get('code')
        lesson_number= request.POST.get("number")
        lesson_title = request.POST.get("title")
        lesson_description=request.POST.get("description")
        video=request.POST.get('video')
        mycourse_object=Course.objects.get(course_name=courselesson)

        if Lesson.objects.filter(lesson_code=lesson_code).exists():
            messages.error(request, 'course_code  already exists.')
            return redirect(request.META.get("HTTP_REFERER"))

        elif Lesson.objects.filter(lesson_number=lesson_number).exists():
            messages.error(request, 'number already exists.')
            return redirect(request.META.get("HTTP_REFERER"))
        

        else:
            lesson = Lesson.objects.create(
            lesson_code=lesson_code,lesson_number=lesson_number,
            lesson_title=lesson_title,course=mycourse_object,lesson_description=lesson_description,
            video=video
            )
        lesson.video=request.FILES.get('video')
        lesson.save()
        return redirect("school:course")
        


class LessonView(View):
    template_name="teacher/lesson.html"

    @method_decorator(staff_only())
    def get(self,request,*args, **kwargs):
        lesson=get_object_or_404(Course,course_name=kwargs['pk']).get_lessons()
        context={"lesson":lesson}
        return render(request,self.template_name,context) 


class LessonDetailView(View):
    template_name="teacher/index.html"

    @method_decorator(staff_only())
    def get(self,request,*args, **kwargs):
        lesson=get_object_or_404(Lesson,lesson_title=kwargs['pk'])
        context={"lesson":lesson,"other":Lesson.objects.all()}
        return render(request,self.template_name,context) 


class DeleteCourseView(DeleteView):
    model = Course
    template_name = 'teacher/deletecourse.html'
    success_url = reverse_lazy('teacher:courses')

class UpdateLessonView(UpdateView):
    model = Lesson
    template_name = 'teacher/updatelesson.html'
    form_class=CourseForm

    @method_decorator(staff_only())
    def get_absolute_url(self):
        return reverse('teacher:teachers')

class DeleteLessonView(DeleteView):
    model = Lesson
    template_name = 'teacher/deletelesson.html'
    success_url = reverse_lazy('teacher:courses')

  
        
       







    

teacher/templates/teacher/courselist.html
{%load static %}

<!doctype html>
<html lang="en">
  <head>

  </head>
  <body>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <title>Table Style</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    <style>
    body{
      font-size:20px;
  font-weight: 300;
    }
      
h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
  
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}


/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
} 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
} 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
     
     </style>
        </head>
        
        <body>
  
        <section>
            <!--for demo wrap-->
            <h1>List of COURSES</h1>
            <div class="tbl-header">
              <table cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                    <th class="text-left">Course_name</th>
                    <th class="text-left">Course_code</th>
                    <th class="text-left">Lecturer</th>
                    <th class="text-left">duration</th>
                    <th class="text-left">Capacity</th>
                    <th class="text-left">View Lesson</th>
                    <th class="text-left">Update Course</th>
                    <th class="text-left">Delete Course</th>
                
                    </tr>
                    </thead>
              </table>
            </div>
            <div class="tbl-content">
              <table cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    {% for course in course %}
     <tr>
        <td class="text-left">{{course.course_name}}</td>
        <td class="text-left">{{course.course_code}}</td>
        <td class="text-left">{{course.lecturer.first_name}}  {{course.lecturer.last_name}}</td>
        <td class="text-left">{{course.duration}}hrs</td>
        <td class="text-left">{{course.capacity}} students</td>
        <td class="text-left"><a href="{% url 'teacher:lessons' course.course_name %}" ><button style="height:40px;" class="btn btn-primary">View</button></a></td>
        <td class="text-left"><a href="{% url 'teacher:update' course.id%}" ><button style="height:40px;" class="btn btn-primary">Update</button></a></td>
        <td class="text-left"><a href="{% url 'teacher:deletecourse' course.id%}" ><button style="height:40px;" class="btn btn-primary">Delete</button></a></td>
       
        </tr>
                  {% endfor %}   
                  
                 
                  
                </tbody>
              </table>
            </div>
          </section>
          
          
               
        
        

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
  </body>
</html>

teacher/templates/teacher/deletecourse.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Booking Form HTML Template</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}" />

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{%static 'css/crud.css'%}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

<!-- </head>
<!-- Bootstrap 5 Contact Form Snippet -->
<style>
	body {
  background: #007bff;
  background: linear-gradient(to right, #0062E6, #33AEFF);
}
</style>
<div class="container px-5 my-5">
	<div class="row justify-content-center">
	  <div class="col-lg-8">
		<div class="card border-0 rounded-3 shadow-lg">
		  <div class="card-body p-4">
			<div class="text-center">
			  <div class="h1 fw-light">Delete Course</div>
			</div>
		
      <p class="card-text"><p>Are you sure you want to delete "{{ object }}"?</p></p>
      <form method="post">{% csrf_token %}
        {{ form }}
        <input class="btn btn-primary" type="submit" value="Confirm">
    </form>
  
		  </div>
		</div>
	  </div>
	</div>
  </div>
  
  <!-- CDN Link to SB Forms Scripts -->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

</html> --> -->

teacher/templates/teacher/lesson.html
{%load static %}

<!doctype html>
<html lang="en">
  <head>

  </head>
  <body>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <title>Table Style</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    <style>
    body{
      font-size:20px;
  font-weight: 300;
    }
      
h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
  
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}


/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
} 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
} 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
     
     </style>
        </head>
        
        <body>
  
        <section>
            <!--for demo wrap-->
            <h1>List of LESSONS</h1>
            <div class="tbl-header">
              <table cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                    <th class="text-left">Lesson_number</th>
                    <th class="text-left">Lesson_code</th>
                    <th class="text-left">lesson_title</th>
                    <th class="text-left">description</th>
                    <th class="text-left">view page</th>
                    <th class="text-left">create lesson</th>
                    <th class="text-left">update lesson</th>
                    <th class="text-left">delete lesson</th>
                
                    </tr>
                    </thead>
              </table>
            </div>
            <div class="tbl-content">
              <table cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    {% for lesson in lesson %}
     <tr>
        <td class="text-left">{{lesson.lesson_number}}</td>
        <td class="text-left">{{lesson.lesson_code}}</td>
        <td class="text-left">{{lesson.lesson_title}}</td>
        <td class="text-left">{{lesson.lesson_description}}</td>
        <td class="text-left"><a href="{% url 'teacher:lessondetails' lesson.lesson_title %}" ><button style="height:40px;" class="btn btn-primary">View</button></a></td>
        <td class="text-left"><a href="{% url 'teacher:createlesson' %}" ><button style="height:40px;" class="btn btn-primary">New lesson</button></a></td>
        <td class="text-left"><a href="{% url 'teacher:updatelesson' lesson.id %}" ><button style="height:40px;" class="btn btn-primary">Update</button></a></td>
        <td class="text-left"><a href="{% url 'teacher:deletelesson' lesson.id %}" ><button style="height:40px;" class="btn btn-primary">Delete</button></a></td>
        </tr>
                  {% endfor %}   
                  
                 
                  
                </tbody>
              </table>
            </div>
          </section>
          
          
               
        
        

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
  </body>
</html>

teacher/templates/teacher/teachersview.html
{%load static %}

<!doctype html>
<html lang="en">
  <head>

  </head>
  <body>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <title>Table Style</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    <style>
      
h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}


/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
} 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
} 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
     
     </style>
        </head>
        
        <body>
  
        <section>
            <!--for demo wrap-->
            <h1>List of Teachers</h1>
            <div class="tbl-header">
              <table cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                    <th class="text-left">email_address</th>
                    <th class="text-left">first_name</th>
                    <th class="text-left">last_name</th>
                    <th class="text-left">phone</th>
                    <th class="text-left">address</th>
                    <th class="text-left">course</th>
                    <th class="text-left">Profile</th>
                    <th class="text-left">Create_Course</th>
                    

                    </tr>
                    </thead>
              </table>
            </div>
            <div class="tbl-content">
              <table cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    {% for teachers in teachers %}
     {%if teachers.is_staff and  teachers.is_superuser is True %}
     <tr>
        <td class="text-left">{{teachers.email}}</td>
        <td class="text-left">{{teachers.first_name}}</td>
        <td class="text-left">{{teachers.last_name}}</td>
        <td class="text-left">{{teachers.phone}}</td>
        <td class="text-left">{{teachers.address}}</td>
        <td class="text-left">{{teachers.course}}</td>
        <td class="text-left"><a href="{%url 'teacher:profile' teachers.index_number %}"><button>Profile</button></a></td>
        <td class="text-left"><a href="{%url 'teacher:createcourse' %}"><button>create</button></a></td>
        </tr>
                  {% endif %}
                  {% endfor %}   
                  
                 
                  
                </tbody>
              </table>
            </div>
          </section>
          
          
               
        
        

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
  </body>
</html>