ELEARN/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("school.urls")),
    path('teacher/', include("teacher.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path
from .import views 

app_name = "school"
urlpatterns=[
    path('home',views.Home.as_view(),name='index'),
    path('about',views.About.as_view(),name='about'),
    path('contact',views.Contacts.as_view(),name='contact'),
    path('course',views.CourseView.as_view(),name='course'),
    path('team',views.Team.as_view(),name='team'),
    path('register',views.RegisterStudentView.as_view(),name='register'),
    path('login',views.LoginView.as_view(),name='login'),
    path('logout',views.LogoutView.as_view(),name='logout'),
    path('lessons/<str:pk>',views.LessonView.as_view(),name="lesson"),
] 

teacher/urls.py
from django.urls import path
from .import views 

app_name = "teacher"
urlpatterns=[
    path('register',views.RegisterTeacherView.as_view(),name='register'),
    path('login',views.LoginView.as_view(),name='login'),
    path('teachers',views.TeachersView.as_view(),name='teachersview'),
    path('createcourse',views.CreateCourseView.as_view(),name='createcourse'),
    path('profile/<str:pk>',views.TeachersDetailsView.as_view(),name="profile"),
    path('createlesson',views.CreateLessonView.as_view(),name="createlesson"),
    path('lessons/<str:pk>',views.LessonView.as_view(),name="lessons"),
    path('lessondetails/<str:pk>',views.LessonDetailView.as_view(),name="lessondetails"),
    path('courses',views.CourseView.as_view(),name="courses"),
    path('update/<str:pk>',views.UpdateCourseView.as_view(),name="update"),
    path('deletecourse/<str:pk>',views.DeleteCourseView.as_view(),name="deletecourse"),
    path('updatelesson/<str:pk>',views.UpdateLessonView.as_view(),name="updatelesson"),
    path('deletelesson/<str:pk>',views.DeleteLessonView.as_view(),name="deletelesson"),
    # path('logout',views.LogoutView.as_view(),name='logout'),
] 

school/models.py
from django.db import models
from django.contrib.auth.models import  AbstractBaseUser,BaseUserManager



class MyUserManager(BaseUserManager):
    def create_user(self,email,password=None,**extra_fields):
        if not email:
            raise ValueError("Provide an email option")

        # if not last_name:  
        #     raise ValueError("Provide a last_name option")

        # if not first_name:
        #     raise ValueError("Provide a first_name option")

        user=self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db) 
        return user

    def create_superuser(self,email,password=None,**extra_fields):
        user=self.create_user(
            email=self.normalize_email(email),
            password=password,
            **extra_fields
        )
        user.is_superuser=True   
        user.is_staff=True
        user.save(using=self._db)
        return user







# Create your models here.
class MyUser(AbstractBaseUser):
   first_name = models.CharField(max_length=200,null=True)
   last_name = models.CharField(max_length=200,null=True)
   phone=models.CharField(max_length=200,null=True,unique=True)
   address=models.CharField(max_length=200,null=True)
   photo=models.ImageField(upload_to="school",blank=True)
   email=models.EmailField(max_length=60,unique=True)
   index_number=models.CharField(max_length=10,unique=True,blank=True, null=True)
   last_login_at = models.DateTimeField(blank=True, null=True)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   is_staff = models.BooleanField(default=False)
   is_superuser = models.BooleanField(default=False)
   is_student = models.BooleanField(default=False)
   is_active = models.BooleanField(default=True)

   USERNAME_FIELD = "email"
   REQUIRED_FIELDS = []

#    REQUIRED_FIELDS=['first_name','last_name']

   objects= MyUserManager()



   def __str__(self):
       return self.first_name or self.email

   def has_perm(self,perm,obj=None):
       return True

       
       
   def has_module_perms(self,app_label):
       return True


class Contact(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    subject=models.CharField(max_length=100)
    message=models.CharField(max_length=500)

    def __str__(self):
        return self.name
        







          
    
    



        

school/views.py
from re import template
from django.shortcuts import render,redirect,get_object_or_404,HttpResponseRedirect
from django.views.generic import View
from school.models   import MyUser,Contact
from teacher.models import Course
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from teacher.dec import students_only
from django.utils.decorators import method_decorator
from teacher.models import Lesson
# Create your views here.


class Home(View):
    template_name="school/index.html"
    def get(self,request):
        context={"myuser":MyUser.objects.all(),"teach":MyUser.objects.all()}
        return render(request,self.template_name,context)

class About(View):
    template_name="school/about.html"
    def get(self,request):
        return render(request,self.template_name)
        
class Contacts(View):
    template_name="school/contact.html"
    def get(self,request):
        return render(request,self.template_name)

    def post(self,request,*args,**kwargs):
        name=request.POST.get('Name')
        subject=request.POST.get('Subject')
        email=request.POST.get('Email')
        message=request.POST.get('Message')

        contact=Contact.objects.create(
            name=name,subject=subject,message=message,email=email
        )
        contact.save()
        return redirect(request.META.get("HTTP_REFERER"))

class CourseView(View):
    template_name="school/courses.html"
    def get(self,request):
        context={"course":Course.objects.all(),"lesson":Lesson.objects.all()}
        return render(request,self.template_name,context)

class Team(View):
    template_name="school/team.html"
    def get(self,request):
        context={"teach":MyUser.objects.all()}
        return render(request,self.template_name,context)


class RegisterStudentView(View):
    template_name="school/register.html"
    def get(self,request):
        return render(request,self.template_name)

    def post(self, request, *args, **kwargs):
        # photo = request.FILES.get("photo")
        email= request.POST.get("email_address")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        phone=request.POST.get("phone")
        photo = request.POST.get("photo")
        address = request.POST.get("address")
        password = request.POST.get("password")
        repeat_password = request.POST.get("repeat_password")

        if password != repeat_password:
            messages.add_message(request, messages.ERROR,
                                 "Passwords do not match.")
            return redirect("school:register")
        else:
            student = MyUser.objects.create(
               first_name=first_name,last_name=last_name,
               phone=phone,photo=photo,address=address, 
               email=email
            )
            student.is_student=True
            student.set_password(password)
           
            student.save()
        return redirect("school:index")

class LoginView(View):
    template_name = "school/login.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email_address")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)

        if user is not None and user.is_student:
            login(request, user)
            redirect_url = "school:index"
            return redirect(redirect_url)
        else:
            messages.add_message(request, messages.ERROR,
                                 "Invalid credentials")
            return render(request, self.template_name)

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect("school:index")


class LessonView(View):
    template_name="school/lesson.html"

    @method_decorator(students_only())
    def get(self,request,*args, **kwargs):
        lesson=get_object_or_404(Course,course_name=kwargs['pk']).get_lessons()
        context={"lesson":lesson}
        return render(request,self.template_name,context)



    

school/templates/school/lesson.html
{%load static %}

<!doctype html>
<html lang="en">
  <head>

  </head>
  <body>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <title>Table Style</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    <style>
    body{
      font-size:20px;
  font-weight: 300;
    }
      
h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
  
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}


/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
} 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
} 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
     
     </style>
        </head>
        
        <body>
  
        <section>
            <!--for demo wrap-->
            <h1>List of LESSONS</h1>
            <div class="tbl-header">
              <table cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                    <th class="text-left">Lesson_number</th>
                    <th class="text-left">Lesson_code</th>
                    <th class="text-left">lesson_title</th>
                    <th class="text-left">view page</th>
                    
                
                    </tr>
                    </thead>
              </table>
            </div>
            <div class="tbl-content">
              <table cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    {% for lesson in lesson %}
     <tr>
        <td class="text-left">{{lesson.lesson_number}}</td>
        <td class="text-left">{{lesson.lesson_code}}</td>
        <td class="text-left">{{lesson.lesson_title}}</td>
        <td class="text-left"><a href="{% url 'teacher:lessondetails' lesson.lesson_title %}" ><button style="height:40px;" class="btn btn-primary">View</button></a></td>
        </tr>
                  {% endfor %}   
                  
                 
                  
                </tbody>
              </table>
            </div>
          </section>
          
          
               
        
        

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
  </body>
</html>

school/templates/school/login.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <title>Login</title>
</head>
<style type="text/css">

  .card-shadow {
    background-color: white;
    -webkit-box-shadow: 0 0 20px 10px #28284125;
    box-shadow: 0 0 20px 10px #28284125;
    padding: 1em;
    border-radius: 4px;
    margin-top: 1.3em;
    max-width: 100vw;
     overflow-y: scroll;
}
</style>



<div class="container"  style="width:45rem">
  <h3 class="text-center"> Please Login as a Student </h3>
      <div class="card card-shadow" style="height:25rem">
        <div class="card-body">
            {% if messages %}
            <div id="message-container" class="col-md-12 mx-auto">
                {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show py-3 mt-2" role="alert">
                <strong>Alert! </strong> {{message}}.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
          <form class="col-md-11 mx-auto" method="post" enctype="multipart/form-data">
            {% csrf_token %}
         
            <label class="font-weight-bold" for="email_address">Email Address</label>
            <input placeholder="email address" type="email"  name="email_address" class="mb-2 form-control-lg form-control  mb-3">
  
  
            <div class="form-group mt-4">
              <label class="font-weight-bold" for="password1"> Password</label>
              <input placeholder="Password" type="password" name="password" id="password1" class="mb-2 form-control-lg form-control mb-3">
            </div>
  
  
          
            <div class="form-group mt-3" ; >
              <button type="submit" class="btn btn-primary">Login</button>
              <a href="{%url 'school:index'%}">
                <button class="btn btn-primary text-white">Cancel</button>
              </a>  
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

</div> 

school/templates/school/team.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>eLEARNING - eLearning HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{%static 'img/favicon.ico'%}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href= 'https://fonts.googleapis.com'>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{%static 'lib/animate/animate.min.css'%}" rel="stylesheet">
    <link href="{%static 'lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{%static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="{%url 'school:index'%}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{%url 'school:index'%}" class="nav-item nav-link ">Home</a>
                <a href="{%url 'school:about'%}" class="nav-item nav-link">About</a>
                <a href="{%url 'school:course'%}" class="nav-item nav-link">Courses</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="{%url 'school:team'%}" class="dropdown-item  active">Our Team</a>
                        
                    </div>
                </div>
                <a href="{%url 'school:contact'%}" class="nav-item nav-link">Contact</a>
            </div>
            <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
        </div>
        </nav>
    <!-- Navbar End -->


    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Our Team</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Team</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- Team Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Instructors</h6>
                <h1 class="mb-5">Expert Instructors</h1>
            </div>
            <div class="row g-4">
                {% for teacher in teach %}
                {% if teacher.is_staff and teacher.is_superuser is False%}
              
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                             <img  style="height: 300px;width: 477px;" class="img-fluid" src="{{teacher.photo.url}}" alt="">
                        </div>
                        <div class="position-relative d-flex justify-content-center" style="margin-top: -23px;">
                            <div class="bg-light d-flex justify-content-center pt-2 px-1">
                                <a class="btn btn-sm-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-sm-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-sm-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">{{teacher.first_name}} {{teacher.last_name}}</h5>
                            <small>Designation</small>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
           
        </div>
    </div>
    <!-- Team End -->
        

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Quick Link</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                    <a class="btn btn-link" href="">FAQs & Help</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Gallery</h4>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/course-1.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/course-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/course-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/course-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/course-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/course-1.jpg" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                        Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

 <!-- JavaScript Libraries -->
 <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
 <script src="{%static 'lib/wow/wow.min.js'%}"></script>
 <script src="{%static 'lib/easing/easing.min.js'%}"></script>
 <script src="{%static 'lib/waypoints/waypoints.min.js'%}"></script>
 <script src="{%static 'lib/owlcarousel/owl.carousel.min.js'%}"></script>

 <!-- Template Javascript -->
 <script src="{%static 'js/main.js'%}"></script>
</body>

</html>